### ISSUE TITLE
what makes this package better than laravel itself?

### ISSUE THREAD

**Issue by michabbb** [victor-falcon/laravel-task#1]
hi,

can you please explain whats the benefit of this package is beside the build-in tools laravel already offers?
I don´t really understand this.

thanks a lot,
micha

**Comment by victor-falcon** [comment]
Well, in Laravel you have Jobs, for example, that are similar in someway, but the have no authentication and validation included. 

Also they are more complex, you can triggered in async mode, which is good, but not useful in controllers, IMO.

**Comment by michabbb** [comment]
is your "task" build on top of "jobs" or is it something completely different that has nothing todo with "jobs" so your tasks, for example, are not queuable?

**Comment by victor-falcon** [comment]
No, it's not based on jobs. This tasks are not queueble. The will be executed always synchronous.

In the future I will add something to make them in batch's or in a pipeline or something. ☺️

**Comment by michabbb** [comment]
okay, thanks for your feedback and helping me to understand 😉
